### ISSUE TITLE
Adding placeholders for command templates

### ISSUE THREAD

**Issue by CaptainQuirk** [laktak/tome#1]
Hi !

I just discovered your project and it looks really great.

What do you think about adding support for variables ?

**Example**  :  

```sh
convert {in} {out}
```

Pressing enter on this line in a playbook would prompt (in vim ? in tmux ?) for both `in` and `out` variable values before executing them.

Filling the variable values could even be facilitated by the use of extracto !

What do you think ?

**Comment by CaptainQuirk** [comment]
I had missed the comment about shell variables, but I think that handling variables via shell functions and shell variables will rapidly clutter playbook files

**Comment by laktak** [comment]
I usually define my variables in the playbook. Without them I would only have "half" of my commands.

Some basic support for variables would be nice though in case the language does not easily support them. I'll think about it.

**Comment by laktak** [comment]
Please take a look at the variable support. You should be able to keep your variable definitions out of your playbooks if you wish.

Undefined variables will open in a scratchbook where you can define them, but will not be saved.

**Comment by CaptainQuirk** [comment]
I'll have a look ! Thanks !
